import { Header } from "@/components/semantic/Header";
import { Footer } from "@/components/semantic/Footer";
import { Main } from "@/components/semantic/Main";
import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { AllProviders } from "@/providers/AllProviders";
import { ScrollProgress } from "@/components/ScrollProgress";

const poppins = Poppins({
  weight: ["100", "400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Name",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AllProviders>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <ScrollProgress />
          <Header />
          <Main>{children}</Main>
          <Footer />
        </body>
      </html>
    </AllProviders>
  );
}
