import { NotFoundView } from "@/views/NotFoundView";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Səhifə tapılmadı",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function NotFound() {
  return <NotFoundView />;
}
